baseurl = "https://www.joehsieh.com/"
title = "JOEHSIEH.COM"
author = "Joseph Hsieh"
copyright = "Â© 2021, Joseph Hsieh, All rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Joe Hsieh"
introDescription = "Welcome! This is where I discuss projects, interests, and my passions"
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
#instagram = ""
linkedin = "joseph-hsieh-49972219"
#twitter = ""
